MemleketKütüphanesi_/Controllers/BookWorksController.cs
using MemleketKütüphanesi_.Models;
using Microsoft.AspNetCore.Mvc;

namespace MemleketKütüphanesi_.Controllers
{
    public class BookWorksController : Controller
    {
        MemleketLibraryContext dB = new MemleketLibraryContext();

        public IActionResult _GetBookList() // Kitap listesini getiren action'dır.
        {
            return View(dB.Books);
        }

        [HttpGet]
        public IActionResult _AddBook() // Kitap ekleme sayfasını getiren action'dır.
        {
            return View("_AddBook");
        }

        [HttpPost]
        public IActionResult _AddBook(Book model) // Book tablosuna kitap ekleyip,kullanıcıya geri mesaj döndürür.
        {
            if (CheckBook(model) == true) // Daha önceden aynı isimde bir kitap varsa buraya girer.
            {
                ViewBag.ErrorMessage = "Bu isimde bir kitap zaten bulunmaktadır.";
                return View("_AddBook");
            }
            else // Daha önce aynı isimde bir kitap kaydı yapılmadıysa kayıt işlemini yapar.
            {
                dB.Books.Add(model);
                dB.SaveChanges();
                ViewBag.SuccessMessage = "Kayıt işlemi başarılı.";
                return View("_AddBook");
            }
        }

        public bool CheckBook(Book model) // Kullanıcının girdiği isimde bir kitabın daha önce kaydedilip,kaydedilmediğini kontrol eder.
        {
            var CheckResult = dB.Books.FirstOrDefault(x => x.Name.Equals(model.Name));

            if (CheckResult == null) // Bu durumda bu isimde bir kitap yok demektir
            {
                return false;
            }
            else // O zaman bu isimde bir kitap var demektir. 
                return true;
        }

        [HttpGet]
        public IActionResult _DeleteBook() // Kitap silme sayfasını getiren action'dır.
        {
            return View("_DeleteBook");
        }

        [HttpPost]
        public IActionResult _DeleteBook(Book model) // Kitap silme işlemi burada yapılır.
        {
            if (CheckBook(model) == true) // Burada kitap kontrolü yapılır ve eğer kitap bulunursa silinecektir.
            {
                var deleteBook = dB.Books.FirstOrDefault(x => x.Name.Equals(model.Name)); // İlk önce gelen kitabın nesnesi yakalanır.
                dB.Books.Remove(deleteBook);
                dB.SaveChanges();
                ViewBag.SuccessMessage = "Kitap silme işlemi başarılı.";
                return View("_DeleteBook");
            }
            else
            {
                ViewBag.ErrorMessage = "Bu isimde bir kitap bulunmamaktadır.";
                return View("_DeleteBook");
            }
        }
    }
}

MemleketKütüphanesi_/Controllers/DashboardController.cs
using Azure.Identity;
using MemleketKütüphanesi_.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;

namespace MemleketKütüphanesi_.Controllers
{
    public class DashboardController : Controller
    {
        MemleketLibraryContext dB = new MemleketLibraryContext(); // Veritabanı referans noktam

        public IActionResult Dashboard() // Dashboard sayfasında sadece sidebar olacak şekilde yükler.
        {
            return View();
        }

        public IActionResult _GetUserList() // User tablosunu listeler.
        {
            return View(dB.Users); // User tablosu içerisindeki bilgileri View'e gönderir.
        }

        public bool CheckUser(User model) // Kullanıcın User tablosunda olup olmadıgını kontrol eder.Kayıt varsa true,yoksa false döndürür.
        {
            string idNo = model.TcNo;

            var user = dB.Users.FirstOrDefault(u => u.TcNo == (idNo));

            if (user != null) // Kullanıcı varsa true dönecektir.
            {
                return true;
            }
            else // Kullanıcı yoksa false dönecektir.
            {
                return false;
            }

        }

        public User GetUserDetails(User model) // Tabloda yer alan kullanıcının bilgilerini geri döndürür.
        {
            var user = dB.Users.FirstOrDefault(x => x.TcNo.Equals(model.TcNo));

            ViewBag.name = user.Name;
            ViewBag.surname = user.Surname;
            ViewBag.tc = user.TcNo;
            ViewBag.email = user.Email;
            ViewBag.gender = user.Gender;
            ViewBag.birthday = user.BirthDay;
            ViewBag.phone = user.PhoneNumber;
            ViewBag.reports = user.ReportsTo;

            return user;
        }

        public User GetUser(User model) // Kullanıcı varsa bilgilerini yoksa hata mesajını döndürür.
        {
            bool CheckUserResult = CheckUser(model); // CheckUser kullanıcının User tablosunda olup olmamasına göre true veya false döndürecek.

            if (CheckUserResult == true) // Kullanıcı varsa modelden gelen kullanıcı bilgilerini geri döndürücem.
            {
                GetUserDetails(model);
                return model;
            }
            else // Eğer kullanıcı yoksa da hata mesajını geri döndürücem.
            {
                ViewBag.ErrorMessage = "Kullanıcı bulunamadı.Lütfen kontrol ediniz.";
                return model;
            }

        }

        #region _UserUpdate

        public IActionResult SetUserUpdate(User model) // Kullanıcının yeni girilen değerlerini kaydererek, günceller.
        {
            //var user = dB.Users.FirstOrDefault(x => x.TcNo.Equals(GetUser(model).TcNo));

            var user = dB.Users.FirstOrDefault(x => x.TcNo == model.TcNo);


            user.Name = model.Name;
            user.Surname = model.Surname;
            user.Email = model.Email;
            user.BirthDay = model.BirthDay;
            user.PhoneNumber = model.PhoneNumber;
            user.ReportsTo = model.ReportsTo;

            dB.SaveChanges();
            ViewBag.SuccessMessage = "Güncelleme işlemi başarılı.";
            return View("_UpdateUser");
        }

        [HttpGet]
        public IActionResult _UpdateUser() // Kullanıcı güncelleştirme sayfasını getiren action'dır.
        {
            return View("_UpdateUser");
        }

        [HttpPost]
        public IActionResult _UpdateUser(User model) // Kullanıcı güncelleştirme işlemi yapan action'dır.
        {
            GetUser(model);
            return View("_UpdateUser");
        }

        #endregion

        #region _UserDelete

        [HttpGet] 
        public IActionResult _DeleteUser() // Kullanıcı silme sayfasını getiren action'dır.
        {
            return View("_DeleteUser");
        }

        [HttpPost]
        public IActionResult _DeleteUser(User model) // Tc no kontrolü yapar kullanıcı varsa bilgilerini,yoksa hata mesajını döndürür.
        {
            GetUser(model);
            return View("_DeleteUser");
        }

        public IActionResult SetDeleteUser(User model) // Kullanıcıyı User tablosundan siler.
        {
            var user = dB.Users.FirstOrDefault(x => x.TcNo.Equals(GetUser(model).TcNo));
            dB.Users.Remove(user);
            dB.SaveChanges();
            ViewBag.DeleteSuccess = "Kullanıcı silme işlemi başarılı.";
            return View("_DeleteUser");
        }

        #endregion
    }
}

MemleketKütüphanesi_/Views/Shared/_DashboardLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>

    <!-- CSS -->
    <link rel="stylesheet" href="style.css">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css">
</head>
<body style="background-color: #e9e7e4;">

    <div class="d-flex">
        <!-- sidebar start -->
        <div class="py-3 px-3" id="left-sidebar" style="min-width: 15%; background-color: #f8f9fa; box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;min-height: 100vh;">
            <!-- <div class="d-flex align-items-center pb-3" style="border-bottom: 1px solid gray;">
                <img src="https://picsum.photos/200/300" class="rounded-circle" alt="" style="width : 40px ;height: 40px;">
                <span class="ms-2 fw-semibold">Kaan Tetik</span>
            </div> -->
            <div id="sidebar-nav">
                <ul class="p-0 m-0 mt-3" style="list-style: none;">
                    <li class="mb-3 pt-3" style="border-top: 1px solid gray;">
                        <i class="fa-solid fa-users fs-5 me-2"></i>
                        <a class="fw-semibold text-dark" asp-controller="Dashboard" asp-action="_GetUserList" style="text-decoration: none;">Üyeleri Listele</a>
                    </li>
                    <li class="fw-semibold mb-3">
                        <i class="fa-solid fa-users-gear fs-5 me-2"></i>
                        <a class="fw-semibold text-dark" asp-controller="Dashboard" asp-action="_UpdateUser" style="text-decoration: none;">Üye Güncelle</a>
                    </li>
                    <li class="fw-semibold mb-3">
                        <i class="fa-solid fa-trash fs-5 me-2"></i>
                        <a class="fw-semibold text-dark" asp-controller="Dashboard" asp-action="_DeleteUser" style="text-decoration: none;">Üye Sil</a>
                    </li>
                    <li class="fw-semibold mb-3">
                        <i class="fa-solid fa-list fs-5 me-2"></i>
                        <a class="fw-semibold text-dark" asp-controller="BookWorks" asp-action="_GetBookList" style="text-decoration: none;">Kitapları Listele</a>
                    </li>
                    <li class="fw-semibold mb-3">
                        <i class="fa-solid fa-book-medical fs-5 me-2"></i>
                        <a class="fw-semibold text-dark" asp-controller="BookWorks" asp-action="_AddBook" style="text-decoration: none;">Kitap Ekle</a>
                    </li>
                    <li class="fw-semibold mb-3 pb-3" style="border-bottom: 1px solid gray;">
                        <i class="fa-solid fa-trash fs-5 me-2"></i>
                        <a class="fw-semibold text-dark" asp-controller="BookWorks" asp-action="_DeleteBook" style="text-decoration: none;">Kitap Sil</a>
                    </li>
                </ul>
                <ul class="p-0 m-0 mt-auto" style="list-style: none;">
                    <li class="fw-semibold mt-auto">
                        <i class="fa-solid fa-right-from-bracket fs-5 me-2"></i>
                        <a class="fw-semibold text-dark" asp-controller="Home" asp-action="Anasayfa" style="text-decoration: none;">Anasayfaya Dön</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- sidebar end -->

            @RenderBody()

    </div>

    <script src="./bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

MemleketKütüphanesi_/Views/Shared/_Layout.cshtml
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>

    <!-- CSS -->
    <link rel="stylesheet" href="~/css/site.css">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css">
  </head>
  <body style="background-color: #f3f3f3;">

        @RenderBody()

    <script src="./bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>

MemleketKütüphanesi_/Views/Shared/_UserDashboard.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>

    <!-- CSS -->
    <link rel="stylesheet" href="style.css">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/font-awesome/css/all.min.css">
</head>
<body style="background-color: #e9e7e4;">

    <div class="d-flex">
        <!-- sidebar start -->
        <div class="py-3 px-3" id="left-sidebar" style="min-width: 15%; background-color: #f8f9fa; box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;min-height: 100vh;">
            <!-- <div class="d-flex align-items-center pb-3" style="border-bottom: 1px solid gray;">
                <img src="https://picsum.photos/200/300" class="rounded-circle" alt="" style="width : 40px ;height: 40px;">
                <span class="ms-2 fw-semibold">Kaan Tetik</span>
            </div> -->
            <div id="sidebar-nav">
                <ul class="p-0 m-0 mt-3" style="list-style: none;">
                    <li class="fw-semibold mb-3">
                        <i class="fa-solid fa-list fs-5 me-2"></i>
                        <a class="fw-semibold text-dark" asp-controller="UserDashboard" asp-action="_GetBookList" style="text-decoration: none;">Kitapları Listele</a>
                    </li>
                </ul>
                <ul class="p-0 m-0 mt-auto" style="list-style: none;">
                    <li class="fw-semibold mt-auto">
                        <i class="fa-solid fa-right-from-bracket fs-5 me-2"></i>
                        <a class="fw-semibold text-dark" asp-controller="Home" asp-action="Anasayfa" style="text-decoration: none;">Anasayfaya Dön</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- sidebar end -->
        @RenderBody()

    </div>

    <script src="./bootstrap/js/bootstrap.min.js"></script>
</body>
</html>